name: Build & Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    uses: austenstone/.github/.github/workflows/node.js.yml@60b5a83b1ceffa3305c5f37bd066a59946e663bc # main
