name: Print Languages
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: ./
        id: list-languages
      - run: echo ${{ join(fromJSON(steps.list-languages.outputs.languages), ', ') }}
